services:

  backend:
    container_name: django-container
    # Build the image using the local Dockerfile
    build: .
    # And give the image a custom name
    image: django-api
    # Always restart container if anything happens
    restart: always
    # Expose the api on port 8000
    ports:
      - 8000:8000
    # Build this image after the database image
    depends_on:
      - database
    # Copy changes made to the project to the image in real-time
    volumes:
      - ./backend:/django/backend
    # Environment variable to pass to the container
    environment:
      DATABASE_URI: mongodb://root:root@database

  database:
    container_name: mongo-container
    # Pull the mongo image from docker hub
    image: mongo
    # Always restart container if anything happens
    restart: always
    # Environment variable to pass to the container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: api
    # Persist data from the container (/data/db) in the local machine (./database)
    volumes:
      - ./.database:/data/db
