# Generated by Django 4.1 on 2022-08-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
        ),
    ]
