# Generated by Django 4.1 on 2022-08-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
