# Generated by Django 4.1 on 2022-08-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
